### ISSUE TITLE
AVL Drumkits crash Ardour when using x42-eq (fil4.lv2) 

### ISSUE THREAD

**Issue by damiangr** [x42/avldrums.lv2#2] opened 2018-01-06 13:14 UTC
Hi,
Combination of this two plugins causes the LV2 host (ardour nightly and latest release and selfbuild , mixbus) to crash  on windows(Win7 64) (cannot check this on linux).

It has something to do with GUI's.  

Steps to reproduce:
1. Insert LV2 Black Pearl or Red Zeppelin on track
2. Insert x42-eq on the same or another track
3. Open both GUI's -> crash 

error in module  suil_win_in_gtk2.dll

Cheers.
Damian

[Ardour-debug.log](https://github.com/x42/avldrums.lv2/files/1608883/Ardour-debug.log)

Update1. : I've downloaded latest binary from site and:
1. intalled them in CommonFiles/LV2   
2. moved them to Ardour/lib/Ardour6/LV2 overwriting old versions

In both cases they crash Ardour.

Update2. : On Fedora in VMware they are working so it seems this is only windows build issue.

**Comment by x42** [comment] 2018-01-06 15:27
Is it only these two plugins or any two plugins with an openGL GUI?  
e.g. two Red Zeppelin's or a mix of  Harrison-XT and x42-eq?

That's an odd crash.  Windows 10? 64 bit?

**Comment by damiangr** [comment] 2018-01-06 15:34
Only these two (Aby drumkit with x42-eq). Any other combination above is working. My system is Win7 64 bit.

**Comment by x42** [comment] 2018-01-06 16:01
OK. I can reproduce this on Windows7. 

Actually two issues. "Failed to instantiate..." (the GUI cannot be created) and the crash is because that error is not handled correctly (the UI wrapper cleans up the GUI which was not created).

As for why a 2nd GUI fails to instantiate, I don't know yet (it only affects embedded plugin GUIs on Windows).

**Comment by damiangr** [comment] 2018-01-06 16:42
It's not urgent for me, just discovered this by accident.  But I have some other issues with plugins in  ardour not related to this one. Can I contact you somehow ? My mai:l greda.damian@wp.pl .

**Comment by x42** [comment] 2018-01-06 16:48
I've found and understood the issue. (All embedded Plugins all register the same Window-Class). Odd that this didn't come up earlier.  I'll fix this later today.

**Comment by x42** [comment] 2018-01-06 18:18
Fixed in 856f794c38a1.

Updating either http://x42-plugins.com/x42/x42-eq or http://x42-plugins.com/x42/x42-avldrums will solve this issue (Mixbus automatically picks the latest version and will ignore the older ones which are bundled with Mixbus itself)

**Closed by x42** 2018-01-06 18:18 UTC
